### ISSUE TITLE
[request] auto detect delimiter

### ISSUE THREAD

**Issue by zzzgit** [shangerxin/config-ini#17]
I hope it can detect by itself the delimiter

**Comment by shangerxin** [comment]
I will investigate it to make sure no regression issue to the existing code. Thank you for the feedbacks.

**Comment by shangerxin** [comment]
Hi @zzzgit ,

The automatic delimiter should work in the previous versions, I have check the relative code. But I have update the readme to let the user know that they can omit the delimiter parameter to the parser. 

If the INI content is needed to serialize again. Suggest to supply the delimiter to the stringify function. Instead of use the default delimiter. 

Thank you for your feedbacks again!
Best regards, 
Erxin (Edwin)

**Comment by zzzgit** [comment]
> d

Thinks, man.
